name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 82.25.110.80
          username: root
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          script: |
            cd /home/user/web/toolboxz.com/public_html
            git reset --hard
            git pull origin main
            chown -R user:user /home/user/web/toolboxz.com/public_html
